## Numpy

Numpy es un paquete/extensión/librería para Python que es extensamente utilizado por la comunidad de ciencia de datos, la cual nos ayuda a trabajar de forma eficiente con arrays, matrices y vectores.   

In [32]:
# 1ero debemos importar la librería (el uso de alias "np" facilita su uso)
import numpy as np

# crea un array a partir de una lista
mi_lista = [1,2,3]
mi_array = np.array(mi_lista)
mi_array


array([1, 2, 3])

In [33]:
# array multidimensional
multi_array = np.array([[7, 8 , 9], [10, 11, 12]])
multi_array

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
# podemos verificar las dimensiones de un array con "shape"
multi_array.shape

(2, 3)

In [35]:
# con la función arange() podemos crear un array de elementos 
# con un intervalo: arange(inicio, final, intervalo)
array_intervalo = np.arange(0, 20, 2)
array_intervalo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# si queremos realizar transformaciones en un array, podemos utilizar
# la función reshape() --> reshape(nro_arrays, nro_items)
reshaped_array = array_intervalo.reshape(2, 5)
reshaped_array

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [37]:
# la función linspace() es similar a arange(), pero se diferencia 
# en que no especificamos el intervalo, sino la cantidad máxima.
# linspace se encarga de generar los intervalos de forma pareja
# linspace(inicio, cantidad_maxima , final)
lin_array = np.linspace(0, 4, 9)
lin_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [38]:
# resize() --> retorna un nuevo array con la(s) forma/dimension(es) especificada(s)
lin_array.resize(3,3)
lin_array

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

Otros ejemplos del uso de Numpy

In [39]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
# crea un array de 1's  de dimensiones 2x3
array_unos = np.ones([2, 3], int)
array_unos

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
# agrega (en cola) nros 2 verticalmente al array de nros 1
np.vstack([array_unos, array_unos *2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [43]:
# agrega (en cola) nros 2 horizontalmente al array de nros 1
np.hstack([array_unos, array_unos *2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

#### Operaciones con arrays de Numpy

* Operaciones básicas con arrays: adición, sustracción, división, multiplicación, potencias

In [44]:
x = np.array([1, 2, 3])
y = np.array([4, 5 ,6])

x + y

array([5, 7, 9])

In [45]:
x**2

array([1, 4, 9])

In [46]:
x.dot(y)

32

In [47]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [48]:
z.shape

(2, 3)

T -> Transpose: cambia la forma/estructura (shape) del array, intercambiando las columnas por las filas

In [49]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [50]:
z.shape

(2, 3)

dtype: permite saber qué tipo de dato almacena el array

In [51]:
z.dtype

dtype('int64')

astype: castea/transforma el tipo de de dato que almacena el array al especificado por parámetro

In [52]:
# transforma array de int64 a float y asigna el valor a cast_z
cast_z = z.astype('f')
cast_z.dtype

dtype('float32')

#### Funciones matemáticas comunes utilizadas en Numpy

In [53]:
a = np.array([-4, -2, 1 , 3, 5])

In [54]:
a.sum()

3

In [55]:
a.max()

5

In [56]:
a.min()

-4

In [57]:
a.mean()

0.6

In [58]:
a.std()

3.2619012860600183

Para encontrar el index del valor mínimo o máximo utilizamos argmin y argmax respetivamente

In [59]:
a.argmin()

0

In [60]:
a.argmax()

4

### Index y Slice 

In [61]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

* Similar a las listas podemos acceder al valor de un elemento con su index. Además, utilizando ":" podemos obtener el rango especificado

In [62]:
s[3], s[5], s[:4], s[2:5], s[-4:], s[-5::-2]

(9,
 25,
 array([0, 1, 4, 9]),
 array([ 4,  9, 16]),
 array([ 81, 100, 121, 144]),
 array([64, 36, 16,  4,  0]))

* Ejemplos con arrays bidimensionales

In [63]:
mi_ab = np.arange(36)
mi_ab.resize((6,6))
mi_ab

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [64]:
mi_ab[2, 2]

14

In [65]:
mi_ab[3, 3:6]

array([21, 22, 23])

In [66]:
mi_ab[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

* También podemos utilizar el operador "[ ]" para aplicar condiciones y asignar nuevos valores

In [67]:
mi_ab[mi_ab > 30]

array([31, 32, 33, 34, 35])

In [68]:
mi_ab[mi_ab > 30] = 30
mi_ab

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copiando datos con Numpy

In [69]:
# copia_array será un slice del array mi_ab
nuevo_array = mi_ab[:3, :3]
nuevo_array

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [70]:
# asignamos el valor 0 a todos los elementos del array
nuevo_array[:] = 0
nuevo_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
# tener presente que la anterior asignación también cambia los valores del array original
mi_ab

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

* Para evitar errores de este tipo, una solución es utilizar copias del array original y así no cambiar sus valores originales

In [72]:
copia_array = mi_ab.copy()
copia_array

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

* Así, si cambiamos alguno de los valores de cualquier elemento del array, éste sólo afectará a la copia

In [73]:
copia_array[:] = 10
print(copia_array)
print('-'*20)
print(mi_ab)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
--------------------
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


#### Iterando arrays

In [74]:
# crea array de dimensiones 4x3, cuyos elementos serán nros aleatorios desde 0 a 9
array_ej = np.random.randint(0, 10, (3,3))
array_ej

array([[9, 3, 3],
       [9, 3, 0],
       [1, 8, 3]])

In [75]:
# ejemplo con for
for fila in array_ej: 
    print(fila)

[9 3 3]
[9 3 0]
[1 8 3]


In [76]:
# utilizando index
for i in range(len(array_ej)):
    print(array_ej[i])

[9 3 3]
[9 3 0]
[1 8 3]


In [77]:
# Combinando ambos
for i, fila in enumerate(array_ej):
    print('fila', i, '-->', fila)

fila 0 --> [9 3 3]
fila 1 --> [9 3 0]
fila 2 --> [1 8 3]


In [78]:
array_ej2 = array_ej**2
array_ej2

array([[81,  9,  9],
       [81,  9,  0],
       [ 1, 64,  9]])

* Iterando sobre dos arrays con zip()

In [79]:
for i, j in zip(array_ej, array_ej2):
    print(i, '+', j, '=', i + j)

[9 3 3] + [81  9  9] = [90 12 12]
[9 3 0] + [81  9  0] = [90 12  0]
[1 8 3] + [ 1 64  9] = [ 2 72 12]
